### ISSUE TITLE
wslgit-for-jetbrains.exe win-generate-mapping makes empty mapping.txt

### ISSUE THREAD

**Issue by walkerus** [Volune/wslgit-for-jetbrains#1]
PhpStorm When a commit writes, '/mnt/c/Users/*/AppData/Local/Temp/git-commit-msg-.txt': No such file or directory

i have /etc/wsl.conf with:

```
[automount]
enabled = true
root = /
```

**Comment by Volune** [comment]
@risamukhametov can you try running `wslgit-for-jetbrains.exe win-generate-mapping` on windows command line? It will generate a configuration file with the disk mapping. (By default it uses `/mnt`)

**Comment by walkerus** [comment]
> @risamukhametov can you try running `wslgit-for-jetbrains.exe win-generate-mapping` on windows command line? It will generate a configuration file with the disk mapping. (By default it uses `/mnt`)

This command generated an empty mapping.txt in C:\Users\*\AppData\Local\wslgit-for-jetbrains

**Comment by Volune** [comment]
With the same wsl.conf, I don't reproduce. The command will generate a mapping.txt file with this content:
```
c /c
```

Can you run `wsl mount` on windows command line and see if the disk mounting point is present?

**Comment by walkerus** [comment]
wsl mount:

`C:\Users\zFire>wsl mount
rootfs on / type lxfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
cgroup on /sys/fs/cgroup type tmpfs (rw,relatime,mode=755)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,relatime,devices)
C:\ on /c type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
D:\ on /d type drvfs (rw,noatime,uid=1000,gid=1000,case=off)`

I inserted  'c /c' into mapping.txt. Everything works, thank you.

**Comment by Volune** [comment]
Glad to hear you have a workaround and thanks for your feedback, I found the bug in the parsing of `mount` output.
